language: node_js

node_js:
  - '8'
env:
  global:
  - secure: f0dqCyNxlafSK75VAXO2us6d7VOeuWiMB4TdaHJpod7xrN+QYwQpr/UzKCxqyy/zycdvRNPiR0I2N/mndSZvGnQe5eFMHppAGil9w/QQSrYIFE+vP2obWKB4FvOapCdkDdBUaX8qhQYudx5c0ohOV0ALiHuwd9PrnQPD4erFMfvp6r3lrRfpbrGAdGsUtn1tL4WrZO66z29hTU7pj13hT4nu0yj2RSN6KeoZEUdUT80oLIPPajpu5+9/7GzCRwrHEZpYD6q4WeSORTy2auuKA0XTGLZnZRYsuiL/v0suVttKyf9UasUFxHcXNbYnY1hDQRhESJo3Cj2hLjRdmFA6Fh2RDzqzXePg32amdIQN5lw1JoN+vz0xU5T0H0Zl8hLZ4A5PtFKKDG9zQMQaimsPbrx9ke7NXdAEbw273kye+IWg8irGr7F690OqjVI3YGHiIjmjAS2/7WI/pdgWZGteEfAbWlGMdMGSOiI1i0VsaYQhspiNP6kwFGgPR8P2y/l4qGhNnrShkMNAeQY6QKMewbUUPW3aE3Q2cyHqMEPV/TpmOdPD09H06+cb15ChED8i7sOqFkaaWvdWr5Uxgnsz0gIeSKUwzn0gi+/x67ob9+H5OaNXkhb54y0VyrZMusVy5zGF/ZeciXcwM/3i0rte+Mkz9KSSwC2S4FqpabDZlPM=

scripts:
  - npm run build

after_success:
  - bash travis/commit.sh
